### PR TITLE
Update version of cirq, azure-storage-blob and azure-core packages

### PR DESCRIPTION
**Pull request by ricardo-espinoza**

### CODE REVIEW

**Comment by vxfield** [comment]
@ricardo-espinoza, please see this issue that is related to the azure-core package version and the test failures dues to `different payload size expected`
#220

**Comment by ricardo-espinoza** [comment]
> @ricardo-espinoza, please see issue #220 that is related to the azure-core package version and the test failures dues to `different payload size expected`

I'm aware of that issue, and that's why this is still a draft. I'll reach out to you offline to discuss options. Unfortunately, we need to move on from version 12.11.0, and find a way to do so without regressing on tests.

**Review by anpaz — APPROVED** [review]
Looks great!

**Pull request merged**
