### PR TITLE
fix: warnings upon importing qsharp

### LINKED ISSUE #185: Example notebook: Warnings when running `import qsharp` for the first time
image

The following cells of the notebook (including the actual simulations) work fine, so it seems like these warnings can be ignored.
Perhaps there is a way to avoid/silence these warnings?

Running in a conda environment under Ubuntu 20.04 (WSL)

### PR DESCRIPTION
**Pull request by ltalirz**
fixes #185 

Importing the `qsharp` python package in the Jupyter notebook example
resulted in various warnings since the `Microsoft.Quantum.Chemistry` Q#
package was not loaded yet.

This is fixed by instructing to autoload the package in the Q# project
file.

### CODE REVIEW

**Comment by ltalirz** [comment]
ping @guenp

**Review by guenp — APPROVED** [review]
Thanks @ltalirz for fixing this!

**Comment by ltalirz** [comment]
Just out of curiosity - how long does it usually take for these jobs to start?

**Pull request merged**
