### PR TITLE
[Port] Fix super() call and target parameter name (#59)

### PR DESCRIPTION
**Pull request by ricardo-espinoza**
Port of pull request #59 into hotfix release branch.

### CODE REVIEW

**Review by vxfield — COMMENTED** [review]
Looks good to me.
I still want to add more unit tests to increase coverage of the Toshiba solver.

**Comment by vxfield** [comment]
Once I get the unit tests ready, I can add them to your branch and this PR, okay?

**Comment by ricardo-espinoza** [comment]
Hi @vxfield, I'd suggest creating a separate pull request to `release/hotfix/v0.16.2104.2` with the new unit tests. That way, we can merge this PR and get the E2E build and validations started in parallel.

**Review by vxfield — APPROVED** [review]

**Comment by vxfield** [comment]
Sounds good. Approved.

**Pull request merged**
