### PR TITLE
feat: Add typed `InputParams` to document available params for Rigetti targets.

### PR DESCRIPTION
**Pull request by dbanty**
The goal was to explicitly document the availability of the `skipQuilc` parameter in a way that is easily discoverable (e.g., by inspecting the signature of `submit`).

If there's a more recommended pattern than using a class for this, I'm happy to swap things around!

### CODE REVIEW

**Review by anpaz — APPROVED** [review]
I would suggest adding another submit test that takes no input_params, to make sure the defaults work correctly.

**Comment by dbanty** [comment]
Thanks for the suggestion @anpaz, I went ahead and added some additional test cases for `input_params`.

**Review by anpaz — APPROVED** [review]

**Comment by anpaz** [comment]
@dbanty, i've approved and trying to merge but it says some checks are still missing. I believe it's because your branch is a bit behind of `main`. Can you please try updating?

**Comment by dbanty** [comment]
Updated!

**Pull request merged**
