### PR TITLE
Workspace.get_targets() returns list of Targets

### PR DESCRIPTION
**Pull request by guenp**
* Workspace.get_targets returns list of available targets
* Add target status info to Target
* Add `Target.refresh()` method to update queue time/availability

Example usage:

```python
[In]
# Get all workspace targets
workspace.get_targets()
```
```stdout
[Out]
[<Target name="ionq.qpu", avg. queue time=5722 s, Available>,
 <Target name="ionq.simulator", avg. queue time=1 s, Available>,
 <Target name="honeywell.hqs-lt-s1", avg. queue time=0 s, Unavailable>,
 <Target name="honeywell.hqs-lt-s1-apival", avg. queue time=1 s, Available>,
 <Target name="honeywell.hqs-lt-s1-sim", avg. queue time=0 s, Available>]
```

```python
[In]
# Get a single target
workspace.get_target("ionq.qpu")
```
```stdout
[Out]
<Target name="ionq.qpu", avg. queue time=5722 s, Available>
```

```
# Refresh the queue time and availability
target.refresh()
```

### CODE REVIEW

**Review by anpaz — APPROVED** [review]
would it make sense to create a `Target` class instead of using a dict for the values returned by `get_targets`?

**Comment by guenp** [comment]
@anpaz, we already have a `Target` class (for the pass-through). We could indeed adapt that class to include the availability, queue time and status and return a list of instances. e.g.
`workspace.get_targets()` would return `[<IonQ target="ionq.simulator">, <Honeywell target="honeywell.hqs-lt-s1-apival">, ...]`

**Comment by guenp** [comment]
@anpaz I made the changes we discussed. Note that for now, only QC targets are supported; QIO targets are not returned. If we want to support QIO targets or solvers we may want to create a follow up PR. Some options: 1. add a `Workspace.get_solvers()` method 2. create dedicated `Microsoft` target class with hard-coded input and output types 3. add a new API route (if it does not yet exist) that returns the valid input/output data formats and encoding info for a given provider/target and dynamically generate Targets.

**Comment by guenp** [comment]
Closing this in favor of #129

**Pull request closed without merging**
